model:
  model_path:
  class_list: ['Text', 'Title', 'Picture', 'Table', 'List-item', 'Page-header', 'Page-footer', 'Section-header', 'Footnote','Caption','Formula']
  class_map: {}
trainer:
  loss:
    class_weight_flag: true
    node_weight:
    edge_weight:
    loss_weight: -1
  save_epoch_freq: 1
  save_step_freq: 5000
  display_freq: 200
  epochs: 10
  eval_display_freq: 200
  eval_print_freq: 200
  print_freq: 200
  scheduler:
    scheduler_type: stairs
    warmup_epochs: 1
  save_dir: /kaggle/working/output
  tensorboard_dir: /kaggle/working/output/tensorboard
datasets:
  train:
    dataset:
      data_root:
        - /kaggle/input/doclaynet/PNG
      label_root:
        - /kaggle/input/doclaynet/COCO
    collate_fn:
      aug_flag: false
  eval:
    dataset:
      data_root:
        - /kaggle/input/doclaynet/PNG
      label_root:
        - /kaggle/input/doclaynet/COCO
